# Generated by Django 3.1.7 on 2021-04-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('mobile_phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('path', models.CharField(max_length=32, verbose_name='路径')),
            ],
        ),
        migrations.CreateModel(
            name='UserTreasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='收藏夹名')),
                ('mobile_phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('path', models.CharField(max_length=32, verbose_name='路径')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
        ),
    ]
