# Generated by Django 3.1.7 on 2021-04-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210426_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(3, '其他'), (2, '收费版'), (1, '免费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '已支付'), (1, '未支付')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='search',
            field=models.CharField(max_length=32, verbose_name='搜索关键字'),
        ),
    ]
