# Generated by Django 3.1.7 on 2021-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210426_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='isvip',
            field=models.BooleanField(default=False, verbose_name='会员'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(2, '收费版'), (1, '免费版'), (3, '其他')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(1, '#000000'), (2, '#ffffff'), (3, '#ebc656'), (4, '#a2d148'), (5, '#20BFA4'), (6, '#7461c2'), (7, '#20bfa3'), (8, '#56b8eb'), (9, '#f28033'), (10, '#ffc0cb')], default=1, verbose_name='颜色'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
