# Generated by Django 3.1.7 on 2021-05-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210509_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
        ),
        migrations.DeleteModel(
            name='UserTreasure',
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '免费版'), (2, '收费版'), (3, '其他')], default=2, verbose_name='收费类型'),
        ),
    ]
